import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApolloClient, InMemoryCache } from "@apollo/client";
import { ThemeSettingsProvider } from "@/context/theme-settings-context";
import { MemoryLaneStateProvider } from "@/context/memory-lane-state-context";
import { TouchScreenProvider } from "@/context/touch-screen-context";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = new ApolloClient({
        uri: process.env.NEXT_PUBLIC_HASURA_URI, 
        headers: {
        'x-hasura-admin-secret': process.env.NEXT_PUBLIC_X_HASURA_ADMIN_SECRET || ""
        },
        cache: new InMemoryCache()
  });
  
  return (
    <html lang="en">
      <body
        className={"antialiased"}>
        
          <ThemeSettingsProvider>
            <MemoryLaneStateProvider>
                <TouchScreenProvider>
                    {children}
                </TouchScreenProvider>            
            </MemoryLaneStateProvider>
          </ThemeSettingsProvider>
        
      </body>
    </html>
  );
}
